name: json-tui
version: "1.4.1"
summary: A json visualizer with a terminal UI.
description: A json visualizer with a terminal UI.

grade: stable
confinement: strict
base: core20

apps:
  json-tui:
    command: usr/bin/json-tui
    plugs:
      - home

parts:
  json-tui:
    plugin: cmake
    source: https://github.com/ArthurSonzogni/json-tui
    source-type: git
    source-depth: 1
    build-packages:
      - build-essential
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release

passthrough:
  title: json-tui
  license: MIT
